media:
  input: src/media
  output: media

content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    views: default
    
  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file

view:
  fields: [ title ]
  primary: title
  sort: [ date, title ]
  default:
    search: ''
    sort: title
    order: desc