media:
  input: src/media
  output: media

content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    
  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file

  - name: favorites
    label: Favorites
    path: _favorites
    type: collection
    
  - name: code
    label: Code
    path: _code
    type: collection

  - name: notes
    label: Notes
    path: _notes
    type: collection

view:
  fields: [ title ]
  primary: title
  sort: [ date, title ]
  default:
    search: ''
    sort: title
    order: desc